package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private String empId;
     private String empName;

    public Employee() {
    }

	
    public Employee(String empId) {
        this.empId = empId;
    }
    public Employee(String empId, String empName) {
       this.empId = empId;
       this.empName = empName;
    }
   
    public String getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(String empId) {
        this.empId = empId;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }




}


