package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeMaster generated by hbm2java
 */
public class EmployeeMaster  implements java.io.Serializable {


     private String empId;
     private StatusMaster statusMaster;
     private String empFname;
     private String empLname;
     private String currenStreetAddress;
     private String currentCity;
     private String currentState;
     private String currentZipcode;
     private String currentCountry;
     private String currentPhone1;
     private String currentPhone2;
     private String currentMob;
     private String currentFax;
     private String permStreetAddress;
     private String permCity;
     private String permState;
     private String permZipcode;
     private String permCountry;
     private String permPhone1;
     private String permPhone2;
     private String permMob;
     private String permFax;
     private String emailId;
     private Date dateOfJoining;
     private Date dateOfLeaving;
     private Set userMasters = new HashSet(0);
     private Set roleMasters = new HashSet(0);

    public EmployeeMaster() {
    }

	
    public EmployeeMaster(String empId, StatusMaster statusMaster, String empFname, String empLname, String currenStreetAddress, String currentCity, String currentState, String currentZipcode, String currentCountry, String currentPhone1, String currentPhone2, String currentMob, String currentFax, String permStreetAddress, String permCity, String permState, String permZipcode, String permCountry, String permPhone1, String permPhone2, String permMob, String permFax, String emailId, Date dateOfJoining, Date dateOfLeaving) {
        this.empId = empId;
        this.statusMaster = statusMaster;
        this.empFname = empFname;
        this.empLname = empLname;
        this.currenStreetAddress = currenStreetAddress;
        this.currentCity = currentCity;
        this.currentState = currentState;
        this.currentZipcode = currentZipcode;
        this.currentCountry = currentCountry;
        this.currentPhone1 = currentPhone1;
        this.currentPhone2 = currentPhone2;
        this.currentMob = currentMob;
        this.currentFax = currentFax;
        this.permStreetAddress = permStreetAddress;
        this.permCity = permCity;
        this.permState = permState;
        this.permZipcode = permZipcode;
        this.permCountry = permCountry;
        this.permPhone1 = permPhone1;
        this.permPhone2 = permPhone2;
        this.permMob = permMob;
        this.permFax = permFax;
        this.emailId = emailId;
        this.dateOfJoining = dateOfJoining;
        this.dateOfLeaving = dateOfLeaving;
    }
    public EmployeeMaster(String empId, StatusMaster statusMaster, String empFname, String empLname, String currenStreetAddress, String currentCity, String currentState, String currentZipcode, String currentCountry, String currentPhone1, String currentPhone2, String currentMob, String currentFax, String permStreetAddress, String permCity, String permState, String permZipcode, String permCountry, String permPhone1, String permPhone2, String permMob, String permFax, String emailId, Date dateOfJoining, Date dateOfLeaving, Set userMasters, Set roleMasters) {
       this.empId = empId;
       this.statusMaster = statusMaster;
       this.empFname = empFname;
       this.empLname = empLname;
       this.currenStreetAddress = currenStreetAddress;
       this.currentCity = currentCity;
       this.currentState = currentState;
       this.currentZipcode = currentZipcode;
       this.currentCountry = currentCountry;
       this.currentPhone1 = currentPhone1;
       this.currentPhone2 = currentPhone2;
       this.currentMob = currentMob;
       this.currentFax = currentFax;
       this.permStreetAddress = permStreetAddress;
       this.permCity = permCity;
       this.permState = permState;
       this.permZipcode = permZipcode;
       this.permCountry = permCountry;
       this.permPhone1 = permPhone1;
       this.permPhone2 = permPhone2;
       this.permMob = permMob;
       this.permFax = permFax;
       this.emailId = emailId;
       this.dateOfJoining = dateOfJoining;
       this.dateOfLeaving = dateOfLeaving;
       this.userMasters = userMasters;
       this.roleMasters = roleMasters;
    }
   
    public String getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(String empId) {
        this.empId = empId;
    }
    public StatusMaster getStatusMaster() {
        return this.statusMaster;
    }
    
    public void setStatusMaster(StatusMaster statusMaster) {
        this.statusMaster = statusMaster;
    }
    public String getEmpFname() {
        return this.empFname;
    }
    
    public void setEmpFname(String empFname) {
        this.empFname = empFname;
    }
    public String getEmpLname() {
        return this.empLname;
    }
    
    public void setEmpLname(String empLname) {
        this.empLname = empLname;
    }
    public String getCurrenStreetAddress() {
        return this.currenStreetAddress;
    }
    
    public void setCurrenStreetAddress(String currenStreetAddress) {
        this.currenStreetAddress = currenStreetAddress;
    }
    public String getCurrentCity() {
        return this.currentCity;
    }
    
    public void setCurrentCity(String currentCity) {
        this.currentCity = currentCity;
    }
    public String getCurrentState() {
        return this.currentState;
    }
    
    public void setCurrentState(String currentState) {
        this.currentState = currentState;
    }
    public String getCurrentZipcode() {
        return this.currentZipcode;
    }
    
    public void setCurrentZipcode(String currentZipcode) {
        this.currentZipcode = currentZipcode;
    }
    public String getCurrentCountry() {
        return this.currentCountry;
    }
    
    public void setCurrentCountry(String currentCountry) {
        this.currentCountry = currentCountry;
    }
    public String getCurrentPhone1() {
        return this.currentPhone1;
    }
    
    public void setCurrentPhone1(String currentPhone1) {
        this.currentPhone1 = currentPhone1;
    }
    public String getCurrentPhone2() {
        return this.currentPhone2;
    }
    
    public void setCurrentPhone2(String currentPhone2) {
        this.currentPhone2 = currentPhone2;
    }
    public String getCurrentMob() {
        return this.currentMob;
    }
    
    public void setCurrentMob(String currentMob) {
        this.currentMob = currentMob;
    }
    public String getCurrentFax() {
        return this.currentFax;
    }
    
    public void setCurrentFax(String currentFax) {
        this.currentFax = currentFax;
    }
    public String getPermStreetAddress() {
        return this.permStreetAddress;
    }
    
    public void setPermStreetAddress(String permStreetAddress) {
        this.permStreetAddress = permStreetAddress;
    }
    public String getPermCity() {
        return this.permCity;
    }
    
    public void setPermCity(String permCity) {
        this.permCity = permCity;
    }
    public String getPermState() {
        return this.permState;
    }
    
    public void setPermState(String permState) {
        this.permState = permState;
    }
    public String getPermZipcode() {
        return this.permZipcode;
    }
    
    public void setPermZipcode(String permZipcode) {
        this.permZipcode = permZipcode;
    }
    public String getPermCountry() {
        return this.permCountry;
    }
    
    public void setPermCountry(String permCountry) {
        this.permCountry = permCountry;
    }
    public String getPermPhone1() {
        return this.permPhone1;
    }
    
    public void setPermPhone1(String permPhone1) {
        this.permPhone1 = permPhone1;
    }
    public String getPermPhone2() {
        return this.permPhone2;
    }
    
    public void setPermPhone2(String permPhone2) {
        this.permPhone2 = permPhone2;
    }
    public String getPermMob() {
        return this.permMob;
    }
    
    public void setPermMob(String permMob) {
        this.permMob = permMob;
    }
    public String getPermFax() {
        return this.permFax;
    }
    
    public void setPermFax(String permFax) {
        this.permFax = permFax;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public Date getDateOfJoining() {
        return this.dateOfJoining;
    }
    
    public void setDateOfJoining(Date dateOfJoining) {
        this.dateOfJoining = dateOfJoining;
    }
    public Date getDateOfLeaving() {
        return this.dateOfLeaving;
    }
    
    public void setDateOfLeaving(Date dateOfLeaving) {
        this.dateOfLeaving = dateOfLeaving;
    }
    public Set getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set userMasters) {
        this.userMasters = userMasters;
    }
    public Set getRoleMasters() {
        return this.roleMasters;
    }
    
    public void setRoleMasters(Set roleMasters) {
        this.roleMasters = roleMasters;
    }




}


