package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MaterialTechGoodwillMaster generated by hbm2java
 */
public class MaterialTechGoodwillMaster  implements java.io.Serializable {


     private String materialGoodwillId;
     private String materialGoodwillDesc;
     private Set sampleTechApprovals = new HashSet(0);
     private Set technicalFeedbackMasters = new HashSet(0);

    public MaterialTechGoodwillMaster() {
    }

	
    public MaterialTechGoodwillMaster(String materialGoodwillId, String materialGoodwillDesc) {
        this.materialGoodwillId = materialGoodwillId;
        this.materialGoodwillDesc = materialGoodwillDesc;
    }
    public MaterialTechGoodwillMaster(String materialGoodwillId, String materialGoodwillDesc, Set sampleTechApprovals, Set technicalFeedbackMasters) {
       this.materialGoodwillId = materialGoodwillId;
       this.materialGoodwillDesc = materialGoodwillDesc;
       this.sampleTechApprovals = sampleTechApprovals;
       this.technicalFeedbackMasters = technicalFeedbackMasters;
    }
   
    public String getMaterialGoodwillId() {
        return this.materialGoodwillId;
    }
    
    public void setMaterialGoodwillId(String materialGoodwillId) {
        this.materialGoodwillId = materialGoodwillId;
    }
    public String getMaterialGoodwillDesc() {
        return this.materialGoodwillDesc;
    }
    
    public void setMaterialGoodwillDesc(String materialGoodwillDesc) {
        this.materialGoodwillDesc = materialGoodwillDesc;
    }
    public Set getSampleTechApprovals() {
        return this.sampleTechApprovals;
    }
    
    public void setSampleTechApprovals(Set sampleTechApprovals) {
        this.sampleTechApprovals = sampleTechApprovals;
    }
    public Set getTechnicalFeedbackMasters() {
        return this.technicalFeedbackMasters;
    }
    
    public void setTechnicalFeedbackMasters(Set technicalFeedbackMasters) {
        this.technicalFeedbackMasters = technicalFeedbackMasters;
    }




}


