package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * OrganizationMaster generated by hbm2java
 */
public class OrganizationMaster  implements java.io.Serializable {


     private String orgId;
     private String orgName;
     private String orgAdd;
     private String state;
     private String zipcode;
     private String country;
     private String phone1;
     private String phone2;
     private String fax;
     private String mail;
     private Set roleMasters = new HashSet(0);

    public OrganizationMaster() {
    }

	
    public OrganizationMaster(String orgId, String orgName, String orgAdd, String state, String zipcode, String country, String phone1, String phone2, String fax, String mail) {
        this.orgId = orgId;
        this.orgName = orgName;
        this.orgAdd = orgAdd;
        this.state = state;
        this.zipcode = zipcode;
        this.country = country;
        this.phone1 = phone1;
        this.phone2 = phone2;
        this.fax = fax;
        this.mail = mail;
    }
    public OrganizationMaster(String orgId, String orgName, String orgAdd, String state, String zipcode, String country, String phone1, String phone2, String fax, String mail, Set roleMasters) {
       this.orgId = orgId;
       this.orgName = orgName;
       this.orgAdd = orgAdd;
       this.state = state;
       this.zipcode = zipcode;
       this.country = country;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.fax = fax;
       this.mail = mail;
       this.roleMasters = roleMasters;
    }
   
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    public String getOrgAdd() {
        return this.orgAdd;
    }
    
    public void setOrgAdd(String orgAdd) {
        this.orgAdd = orgAdd;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Set getRoleMasters() {
        return this.roleMasters;
    }
    
    public void setRoleMasters(Set roleMasters) {
        this.roleMasters = roleMasters;
    }




}


