package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RatingMaster generated by hbm2java
 */
public class RatingMaster  implements java.io.Serializable {


     private String ratingId;
     private String ratingDesc;
     private Set sampleFinancialApprovals = new HashSet(0);
     private Set sampleProductionApprovals = new HashSet(0);
     private Set technicalFeedbackMasters = new HashSet(0);
     private Set sampleTechApprovals = new HashSet(0);
     private Set financialFeedbackMasters = new HashSet(0);

    public RatingMaster() {
    }

	
    public RatingMaster(String ratingId, String ratingDesc) {
        this.ratingId = ratingId;
        this.ratingDesc = ratingDesc;
    }
    public RatingMaster(String ratingId, String ratingDesc, Set sampleFinancialApprovals, Set sampleProductionApprovals, Set technicalFeedbackMasters, Set sampleTechApprovals, Set financialFeedbackMasters) {
       this.ratingId = ratingId;
       this.ratingDesc = ratingDesc;
       this.sampleFinancialApprovals = sampleFinancialApprovals;
       this.sampleProductionApprovals = sampleProductionApprovals;
       this.technicalFeedbackMasters = technicalFeedbackMasters;
       this.sampleTechApprovals = sampleTechApprovals;
       this.financialFeedbackMasters = financialFeedbackMasters;
    }
   
    public String getRatingId() {
        return this.ratingId;
    }
    
    public void setRatingId(String ratingId) {
        this.ratingId = ratingId;
    }
    public String getRatingDesc() {
        return this.ratingDesc;
    }
    
    public void setRatingDesc(String ratingDesc) {
        this.ratingDesc = ratingDesc;
    }
    public Set getSampleFinancialApprovals() {
        return this.sampleFinancialApprovals;
    }
    
    public void setSampleFinancialApprovals(Set sampleFinancialApprovals) {
        this.sampleFinancialApprovals = sampleFinancialApprovals;
    }
    public Set getSampleProductionApprovals() {
        return this.sampleProductionApprovals;
    }
    
    public void setSampleProductionApprovals(Set sampleProductionApprovals) {
        this.sampleProductionApprovals = sampleProductionApprovals;
    }
    public Set getTechnicalFeedbackMasters() {
        return this.technicalFeedbackMasters;
    }
    
    public void setTechnicalFeedbackMasters(Set technicalFeedbackMasters) {
        this.technicalFeedbackMasters = technicalFeedbackMasters;
    }
    public Set getSampleTechApprovals() {
        return this.sampleTechApprovals;
    }
    
    public void setSampleTechApprovals(Set sampleTechApprovals) {
        this.sampleTechApprovals = sampleTechApprovals;
    }
    public Set getFinancialFeedbackMasters() {
        return this.financialFeedbackMasters;
    }
    
    public void setFinancialFeedbackMasters(Set financialFeedbackMasters) {
        this.financialFeedbackMasters = financialFeedbackMasters;
    }




}


