package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RequirementAnalysisInitiation generated by hbm2java
 */
public class RequirementAnalysisInitiation  implements java.io.Serializable {


     private String reqId;
     private RequirementMaster requirementMaster;
     private String statusId;
     private String statusChangedBy;
     private Date statusChangedDate;
     private String remark;

    public RequirementAnalysisInitiation() {
    }

    public RequirementAnalysisInitiation(String reqId, RequirementMaster requirementMaster, String statusId, String statusChangedBy, Date statusChangedDate, String remark) {
       this.reqId = reqId;
       this.requirementMaster = requirementMaster;
       this.statusId = statusId;
       this.statusChangedBy = statusChangedBy;
       this.statusChangedDate = statusChangedDate;
       this.remark = remark;
    }
   
    public String getReqId() {
        return this.reqId;
    }
    
    public void setReqId(String reqId) {
        this.reqId = reqId;
    }
    public RequirementMaster getRequirementMaster() {
        return this.requirementMaster;
    }
    
    public void setRequirementMaster(RequirementMaster requirementMaster) {
        this.requirementMaster = requirementMaster;
    }
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
    public String getStatusChangedBy() {
        return this.statusChangedBy;
    }
    
    public void setStatusChangedBy(String statusChangedBy) {
        this.statusChangedBy = statusChangedBy;
    }
    public Date getStatusChangedDate() {
        return this.statusChangedDate;
    }
    
    public void setStatusChangedDate(Date statusChangedDate) {
        this.statusChangedDate = statusChangedDate;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


