package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RequirementPriorityMaster generated by hbm2java
 */
public class RequirementPriorityMaster  implements java.io.Serializable {


     private String RPriorityId;
     private String RPriorityDesc;
     private Set requirementMasters = new HashSet(0);

    public RequirementPriorityMaster() {
    }

	
    public RequirementPriorityMaster(String RPriorityId, String RPriorityDesc) {
        this.RPriorityId = RPriorityId;
        this.RPriorityDesc = RPriorityDesc;
    }
    public RequirementPriorityMaster(String RPriorityId, String RPriorityDesc, Set requirementMasters) {
       this.RPriorityId = RPriorityId;
       this.RPriorityDesc = RPriorityDesc;
       this.requirementMasters = requirementMasters;
    }
   
    public String getRPriorityId() {
        return this.RPriorityId;
    }
    
    public void setRPriorityId(String RPriorityId) {
        this.RPriorityId = RPriorityId;
    }
    public String getRPriorityDesc() {
        return this.RPriorityDesc;
    }
    
    public void setRPriorityDesc(String RPriorityDesc) {
        this.RPriorityDesc = RPriorityDesc;
    }
    public Set getRequirementMasters() {
        return this.requirementMasters;
    }
    
    public void setRequirementMasters(Set requirementMasters) {
        this.requirementMasters = requirementMasters;
    }




}


