package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ResourceMaster generated by hbm2java
 */
public class ResourceMaster  implements java.io.Serializable {


     private String rescId;
     private String gorupEnglish;
     private String rescNameEnglish;
     private String link;
     private String showInMenu;
     private Set userMasters = new HashSet(0);
     private Set roleResourceMaps = new HashSet(0);

    public ResourceMaster() {
    }

	
    public ResourceMaster(String rescId, String gorupEnglish, String rescNameEnglish, String link, String showInMenu) {
        this.rescId = rescId;
        this.gorupEnglish = gorupEnglish;
        this.rescNameEnglish = rescNameEnglish;
        this.link = link;
        this.showInMenu = showInMenu;
    }
    public ResourceMaster(String rescId, String gorupEnglish, String rescNameEnglish, String link, String showInMenu, Set userMasters, Set roleResourceMaps) {
       this.rescId = rescId;
       this.gorupEnglish = gorupEnglish;
       this.rescNameEnglish = rescNameEnglish;
       this.link = link;
       this.showInMenu = showInMenu;
       this.userMasters = userMasters;
       this.roleResourceMaps = roleResourceMaps;
    }
   
    public String getRescId() {
        return this.rescId;
    }
    
    public void setRescId(String rescId) {
        this.rescId = rescId;
    }
    public String getGorupEnglish() {
        return this.gorupEnglish;
    }
    
    public void setGorupEnglish(String gorupEnglish) {
        this.gorupEnglish = gorupEnglish;
    }
    public String getRescNameEnglish() {
        return this.rescNameEnglish;
    }
    
    public void setRescNameEnglish(String rescNameEnglish) {
        this.rescNameEnglish = rescNameEnglish;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getShowInMenu() {
        return this.showInMenu;
    }
    
    public void setShowInMenu(String showInMenu) {
        this.showInMenu = showInMenu;
    }
    public Set getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set userMasters) {
        this.userMasters = userMasters;
    }
    public Set getRoleResourceMaps() {
        return this.roleResourceMaps;
    }
    
    public void setRoleResourceMaps(Set roleResourceMaps) {
        this.roleResourceMaps = roleResourceMaps;
    }




}


