package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA



/**
 * RfqStatusMaster generated by hbm2java
 */
public class RfqStatusMaster  implements java.io.Serializable {


     private String rfqStatusId;
     private String rfqStatusRemark;
     private String rfqStatus;
     private String weightage;

    public RfqStatusMaster() {
    }

    public RfqStatusMaster(String rfqStatusId, String rfqStatusRemark, String rfqStatus, String weightage) {
       this.rfqStatusId = rfqStatusId;
       this.rfqStatusRemark = rfqStatusRemark;
       this.rfqStatus = rfqStatus;
       this.weightage = weightage;
    }
   
    public String getRfqStatusId() {
        return this.rfqStatusId;
    }
    
    public void setRfqStatusId(String rfqStatusId) {
        this.rfqStatusId = rfqStatusId;
    }
    public String getRfqStatusRemark() {
        return this.rfqStatusRemark;
    }
    
    public void setRfqStatusRemark(String rfqStatusRemark) {
        this.rfqStatusRemark = rfqStatusRemark;
    }
    public String getRfqStatus() {
        return this.rfqStatus;
    }
    
    public void setRfqStatus(String rfqStatus) {
        this.rfqStatus = rfqStatus;
    }
    public String getWeightage() {
        return this.weightage;
    }
    
    public void setWeightage(String weightage) {
        this.weightage = weightage;
    }




}


