package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA



/**
 * RoleResourceMap generated by hbm2java
 */
public class RoleResourceMap  implements java.io.Serializable {


     private String roleResourceMapId;
     private RoleMaster roleMaster;
     private ResourceMaster resourceMaster;

    public RoleResourceMap() {
    }

    public RoleResourceMap(String roleResourceMapId, RoleMaster roleMaster, ResourceMaster resourceMaster) {
       this.roleResourceMapId = roleResourceMapId;
       this.roleMaster = roleMaster;
       this.resourceMaster = resourceMaster;
    }
   
    public String getRoleResourceMapId() {
        return this.roleResourceMapId;
    }
    
    public void setRoleResourceMapId(String roleResourceMapId) {
        this.roleResourceMapId = roleResourceMapId;
    }
    public RoleMaster getRoleMaster() {
        return this.roleMaster;
    }
    
    public void setRoleMaster(RoleMaster roleMaster) {
        this.roleMaster = roleMaster;
    }
    public ResourceMaster getResourceMaster() {
        return this.resourceMaster;
    }
    
    public void setResourceMaster(ResourceMaster resourceMaster) {
        this.resourceMaster = resourceMaster;
    }




}


