package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RoleMaster generated by hbm2java
 */
public class RoleMaster  implements java.io.Serializable {


     private String roleId;
     private OrganizationMaster organizationMaster;
     private String roleName;
     private String roleDesc;
     private String statusId;
     private Set employeeMasters = new HashSet(0);
     private Set roleResourceMaps = new HashSet(0);

    public RoleMaster() {
    }

	
    public RoleMaster(String roleId, OrganizationMaster organizationMaster, String roleName, String roleDesc, String statusId) {
        this.roleId = roleId;
        this.organizationMaster = organizationMaster;
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.statusId = statusId;
    }
    public RoleMaster(String roleId, OrganizationMaster organizationMaster, String roleName, String roleDesc, String statusId, Set employeeMasters, Set roleResourceMaps) {
       this.roleId = roleId;
       this.organizationMaster = organizationMaster;
       this.roleName = roleName;
       this.roleDesc = roleDesc;
       this.statusId = statusId;
       this.employeeMasters = employeeMasters;
       this.roleResourceMaps = roleResourceMaps;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public OrganizationMaster getOrganizationMaster() {
        return this.organizationMaster;
    }
    
    public void setOrganizationMaster(OrganizationMaster organizationMaster) {
        this.organizationMaster = organizationMaster;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleDesc() {
        return this.roleDesc;
    }
    
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
    public Set getEmployeeMasters() {
        return this.employeeMasters;
    }
    
    public void setEmployeeMasters(Set employeeMasters) {
        this.employeeMasters = employeeMasters;
    }
    public Set getRoleResourceMaps() {
        return this.roleResourceMaps;
    }
    
    public void setRoleResourceMaps(Set roleResourceMaps) {
        this.roleResourceMaps = roleResourceMaps;
    }




}


