package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SalutaionMaster generated by hbm2java
 */
public class SalutaionMaster  implements java.io.Serializable {


     private String salutationId;
     private String salutationDesc;
     private Set supplierContactMasters = new HashSet(0);
     private Set supplierContactMasters_1 = new HashSet(0);

    public SalutaionMaster() {
    }

	
    public SalutaionMaster(String salutationId, String salutationDesc) {
        this.salutationId = salutationId;
        this.salutationDesc = salutationDesc;
    }
    public SalutaionMaster(String salutationId, String salutationDesc, Set supplierContactMasters, Set supplierContactMasters_1) {
       this.salutationId = salutationId;
       this.salutationDesc = salutationDesc;
       this.supplierContactMasters = supplierContactMasters;
       this.supplierContactMasters_1 = supplierContactMasters_1;
    }
   
    public String getSalutationId() {
        return this.salutationId;
    }
    
    public void setSalutationId(String salutationId) {
        this.salutationId = salutationId;
    }
    public String getSalutationDesc() {
        return this.salutationDesc;
    }
    
    public void setSalutationDesc(String salutationDesc) {
        this.salutationDesc = salutationDesc;
    }
    public Set getSupplierContactMasters() {
        return this.supplierContactMasters;
    }
    
    public void setSupplierContactMasters(Set supplierContactMasters) {
        this.supplierContactMasters = supplierContactMasters;
    }
    public Set getSupplierContactMasters_1() {
        return this.supplierContactMasters_1;
    }
    
    public void setSupplierContactMasters_1(Set supplierContactMasters_1) {
        this.supplierContactMasters_1 = supplierContactMasters_1;
    }




}


