package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SampleTechApproval generated by hbm2java
 */
public class SampleTechApproval  implements java.io.Serializable {


     private String sampleTechApprovalId;
     private SupplierQuatationMaster supplierQuatationMaster;
     private RatingMaster ratingMaster;
     private MaterialTechGoodwillMaster materialTechGoodwillMaster;
     private String sampleTechApproved;
     private String feedback;
     private String sampleTechApprovedBy;
     private Date dateOn;

    public SampleTechApproval() {
    }

    public SampleTechApproval(String sampleTechApprovalId, SupplierQuatationMaster supplierQuatationMaster, RatingMaster ratingMaster, MaterialTechGoodwillMaster materialTechGoodwillMaster, String sampleTechApproved, String feedback, String sampleTechApprovedBy, Date dateOn) {
       this.sampleTechApprovalId = sampleTechApprovalId;
       this.supplierQuatationMaster = supplierQuatationMaster;
       this.ratingMaster = ratingMaster;
       this.materialTechGoodwillMaster = materialTechGoodwillMaster;
       this.sampleTechApproved = sampleTechApproved;
       this.feedback = feedback;
       this.sampleTechApprovedBy = sampleTechApprovedBy;
       this.dateOn = dateOn;
    }
   
    public String getSampleTechApprovalId() {
        return this.sampleTechApprovalId;
    }
    
    public void setSampleTechApprovalId(String sampleTechApprovalId) {
        this.sampleTechApprovalId = sampleTechApprovalId;
    }
    public SupplierQuatationMaster getSupplierQuatationMaster() {
        return this.supplierQuatationMaster;
    }
    
    public void setSupplierQuatationMaster(SupplierQuatationMaster supplierQuatationMaster) {
        this.supplierQuatationMaster = supplierQuatationMaster;
    }
    public RatingMaster getRatingMaster() {
        return this.ratingMaster;
    }
    
    public void setRatingMaster(RatingMaster ratingMaster) {
        this.ratingMaster = ratingMaster;
    }
    public MaterialTechGoodwillMaster getMaterialTechGoodwillMaster() {
        return this.materialTechGoodwillMaster;
    }
    
    public void setMaterialTechGoodwillMaster(MaterialTechGoodwillMaster materialTechGoodwillMaster) {
        this.materialTechGoodwillMaster = materialTechGoodwillMaster;
    }
    public String getSampleTechApproved() {
        return this.sampleTechApproved;
    }
    
    public void setSampleTechApproved(String sampleTechApproved) {
        this.sampleTechApproved = sampleTechApproved;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public String getSampleTechApprovedBy() {
        return this.sampleTechApprovedBy;
    }
    
    public void setSampleTechApprovedBy(String sampleTechApprovedBy) {
        this.sampleTechApprovedBy = sampleTechApprovedBy;
    }
    public Date getDateOn() {
        return this.dateOn;
    }
    
    public void setDateOn(Date dateOn) {
        this.dateOn = dateOn;
    }




}


