package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SampleFinancialApproval generated by hbm2java
 */
public class SampleFinancialApproval  implements java.io.Serializable {


     private String sampleFinancApprovalId;
     private SupplierQuatationMaster supplierQuatationMaster;
     private RatingMaster ratingMaster;
     private FinancialGoodwillMaster financialGoodwillMaster;
     private String sampleFinancApproved;
     private String feedback;
     private String sampleFinancApprovedBy;
     private Date dateOn;

    public SampleFinancialApproval() {
    }

    public SampleFinancialApproval(String sampleFinancApprovalId, SupplierQuatationMaster supplierQuatationMaster, RatingMaster ratingMaster, FinancialGoodwillMaster financialGoodwillMaster, String sampleFinancApproved, String feedback, String sampleFinancApprovedBy, Date dateOn) {
       this.sampleFinancApprovalId = sampleFinancApprovalId;
       this.supplierQuatationMaster = supplierQuatationMaster;
       this.ratingMaster = ratingMaster;
       this.financialGoodwillMaster = financialGoodwillMaster;
       this.sampleFinancApproved = sampleFinancApproved;
       this.feedback = feedback;
       this.sampleFinancApprovedBy = sampleFinancApprovedBy;
       this.dateOn = dateOn;
    }
   
    public String getSampleFinancApprovalId() {
        return this.sampleFinancApprovalId;
    }
    
    public void setSampleFinancApprovalId(String sampleFinancApprovalId) {
        this.sampleFinancApprovalId = sampleFinancApprovalId;
    }
    public SupplierQuatationMaster getSupplierQuatationMaster() {
        return this.supplierQuatationMaster;
    }
    
    public void setSupplierQuatationMaster(SupplierQuatationMaster supplierQuatationMaster) {
        this.supplierQuatationMaster = supplierQuatationMaster;
    }
    public RatingMaster getRatingMaster() {
        return this.ratingMaster;
    }
    
    public void setRatingMaster(RatingMaster ratingMaster) {
        this.ratingMaster = ratingMaster;
    }
    public FinancialGoodwillMaster getFinancialGoodwillMaster() {
        return this.financialGoodwillMaster;
    }
    
    public void setFinancialGoodwillMaster(FinancialGoodwillMaster financialGoodwillMaster) {
        this.financialGoodwillMaster = financialGoodwillMaster;
    }
    public String getSampleFinancApproved() {
        return this.sampleFinancApproved;
    }
    
    public void setSampleFinancApproved(String sampleFinancApproved) {
        this.sampleFinancApproved = sampleFinancApproved;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public String getSampleFinancApprovedBy() {
        return this.sampleFinancApprovedBy;
    }
    
    public void setSampleFinancApprovedBy(String sampleFinancApprovedBy) {
        this.sampleFinancApprovedBy = sampleFinancApprovedBy;
    }
    public Date getDateOn() {
        return this.dateOn;
    }
    
    public void setDateOn(Date dateOn) {
        this.dateOn = dateOn;
    }




}


