package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SampleAdminApproval generated by hbm2java
 */
public class SampleAdminApproval  implements java.io.Serializable {


     private String sampleAdminApprovalId;
     private SupplierQuatationMaster supplierQuatationMaster;
     private String sampleAdminApproved;
     private String feedback;
     private String sampleAdminApprovedBy;
     private Date dateOn;

    public SampleAdminApproval() {
    }

    public SampleAdminApproval(String sampleAdminApprovalId, SupplierQuatationMaster supplierQuatationMaster, String sampleAdminApproved, String feedback, String sampleAdminApprovedBy, Date dateOn) {
       this.sampleAdminApprovalId = sampleAdminApprovalId;
       this.supplierQuatationMaster = supplierQuatationMaster;
       this.sampleAdminApproved = sampleAdminApproved;
       this.feedback = feedback;
       this.sampleAdminApprovedBy = sampleAdminApprovedBy;
       this.dateOn = dateOn;
    }
   
    public String getSampleAdminApprovalId() {
        return this.sampleAdminApprovalId;
    }
    
    public void setSampleAdminApprovalId(String sampleAdminApprovalId) {
        this.sampleAdminApprovalId = sampleAdminApprovalId;
    }
    public SupplierQuatationMaster getSupplierQuatationMaster() {
        return this.supplierQuatationMaster;
    }
    
    public void setSupplierQuatationMaster(SupplierQuatationMaster supplierQuatationMaster) {
        this.supplierQuatationMaster = supplierQuatationMaster;
    }
    public String getSampleAdminApproved() {
        return this.sampleAdminApproved;
    }
    
    public void setSampleAdminApproved(String sampleAdminApproved) {
        this.sampleAdminApproved = sampleAdminApproved;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public String getSampleAdminApprovedBy() {
        return this.sampleAdminApprovedBy;
    }
    
    public void setSampleAdminApprovedBy(String sampleAdminApprovedBy) {
        this.sampleAdminApprovedBy = sampleAdminApprovedBy;
    }
    public Date getDateOn() {
        return this.dateOn;
    }
    
    public void setDateOn(Date dateOn) {
        this.dateOn = dateOn;
    }




}


