package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SampleAdminRequest generated by hbm2java
 */
public class SampleAdminRequest  implements java.io.Serializable {


     private String sampleId;
     private SupplierQuatationMaster supplierQuatationMaster;
     private Set sampleDemandSpecfications = new HashSet(0);

    public SampleAdminRequest() {
    }

	
    public SampleAdminRequest(String sampleId, SupplierQuatationMaster supplierQuatationMaster) {
        this.sampleId = sampleId;
        this.supplierQuatationMaster = supplierQuatationMaster;
    }
    public SampleAdminRequest(String sampleId, SupplierQuatationMaster supplierQuatationMaster, Set sampleDemandSpecfications) {
       this.sampleId = sampleId;
       this.supplierQuatationMaster = supplierQuatationMaster;
       this.sampleDemandSpecfications = sampleDemandSpecfications;
    }
   
    public String getSampleId() {
        return this.sampleId;
    }
    
    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }
    public SupplierQuatationMaster getSupplierQuatationMaster() {
        return this.supplierQuatationMaster;
    }
    
    public void setSupplierQuatationMaster(SupplierQuatationMaster supplierQuatationMaster) {
        this.supplierQuatationMaster = supplierQuatationMaster;
    }
    public Set getSampleDemandSpecfications() {
        return this.sampleDemandSpecfications;
    }
    
    public void setSampleDemandSpecfications(Set sampleDemandSpecfications) {
        this.sampleDemandSpecfications = sampleDemandSpecfications;
    }




}


