package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SampleDemandSpecfication generated by hbm2java
 */
public class SampleDemandSpecfication  implements java.io.Serializable {


     private String sampleDemandId;
     private SampleAdminRequest sampleAdminRequest;
     private UnitMeasureMaster unitMeasureMaster;
     private Date sampleExpectedSendingDate;
     private String quantity;

    public SampleDemandSpecfication() {
    }

    public SampleDemandSpecfication(String sampleDemandId, SampleAdminRequest sampleAdminRequest, UnitMeasureMaster unitMeasureMaster, Date sampleExpectedSendingDate, String quantity) {
       this.sampleDemandId = sampleDemandId;
       this.sampleAdminRequest = sampleAdminRequest;
       this.unitMeasureMaster = unitMeasureMaster;
       this.sampleExpectedSendingDate = sampleExpectedSendingDate;
       this.quantity = quantity;
    }
   
    public String getSampleDemandId() {
        return this.sampleDemandId;
    }
    
    public void setSampleDemandId(String sampleDemandId) {
        this.sampleDemandId = sampleDemandId;
    }
    public SampleAdminRequest getSampleAdminRequest() {
        return this.sampleAdminRequest;
    }
    
    public void setSampleAdminRequest(SampleAdminRequest sampleAdminRequest) {
        this.sampleAdminRequest = sampleAdminRequest;
    }
    public UnitMeasureMaster getUnitMeasureMaster() {
        return this.unitMeasureMaster;
    }
    
    public void setUnitMeasureMaster(UnitMeasureMaster unitMeasureMaster) {
        this.unitMeasureMaster = unitMeasureMaster;
    }
    public Date getSampleExpectedSendingDate() {
        return this.sampleExpectedSendingDate;
    }
    
    public void setSampleExpectedSendingDate(Date sampleExpectedSendingDate) {
        this.sampleExpectedSendingDate = sampleExpectedSendingDate;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }




}


