package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SampleRequisitionAcceptanceDetails generated by hbm2java
 */
public class SampleRequisitionAcceptanceDetails  implements java.io.Serializable {


     private String sampleReqId;
     private UnitMeasureMaster unitMeasureMaster;
     private Date sampleExpectedSendingDate;
     private String quantity;

    public SampleRequisitionAcceptanceDetails() {
    }

    public SampleRequisitionAcceptanceDetails(String sampleReqId, UnitMeasureMaster unitMeasureMaster, Date sampleExpectedSendingDate, String quantity) {
       this.sampleReqId = sampleReqId;
       this.unitMeasureMaster = unitMeasureMaster;
       this.sampleExpectedSendingDate = sampleExpectedSendingDate;
       this.quantity = quantity;
    }
   
    public String getSampleReqId() {
        return this.sampleReqId;
    }
    
    public void setSampleReqId(String sampleReqId) {
        this.sampleReqId = sampleReqId;
    }
    public UnitMeasureMaster getUnitMeasureMaster() {
        return this.unitMeasureMaster;
    }
    
    public void setUnitMeasureMaster(UnitMeasureMaster unitMeasureMaster) {
        this.unitMeasureMaster = unitMeasureMaster;
    }
    public Date getSampleExpectedSendingDate() {
        return this.sampleExpectedSendingDate;
    }
    
    public void setSampleExpectedSendingDate(Date sampleExpectedSendingDate) {
        this.sampleExpectedSendingDate = sampleExpectedSendingDate;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }




}


