package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * StatusMaster generated by hbm2java
 */
public class StatusMaster  implements java.io.Serializable {


     private String statusId;
     private String statusDesc;
     private Set quotationAnalysisInitiations = new HashSet(0);
     private Set employeeMasters = new HashSet(0);

    public StatusMaster() {
    }

	
    public StatusMaster(String statusId) {
        this.statusId = statusId;
    }
    public StatusMaster(String statusId, String statusDesc, Set quotationAnalysisInitiations, Set employeeMasters) {
       this.statusId = statusId;
       this.statusDesc = statusDesc;
       this.quotationAnalysisInitiations = quotationAnalysisInitiations;
       this.employeeMasters = employeeMasters;
    }
   
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
    public String getStatusDesc() {
        return this.statusDesc;
    }
    
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }
    public Set getQuotationAnalysisInitiations() {
        return this.quotationAnalysisInitiations;
    }
    
    public void setQuotationAnalysisInitiations(Set quotationAnalysisInitiations) {
        this.quotationAnalysisInitiations = quotationAnalysisInitiations;
    }
    public Set getEmployeeMasters() {
        return this.employeeMasters;
    }
    
    public void setEmployeeMasters(Set employeeMasters) {
        this.employeeMasters = employeeMasters;
    }




}


