package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA



/**
 * SupplierContactMaster generated by hbm2java
 */
public class SupplierContactMaster  implements java.io.Serializable {


     private String contactPersonId;
     private SalutaionMaster salutaionMaster;
     private String suppId;
     private String contactPersonFname;
     private String contactPersonLname;
     private String contactPersonFunction;
     private int contactPersonPhone;
     private String contactPersonEmail;
     private String termsandcondition;

    public SupplierContactMaster() {
    }

    public SupplierContactMaster(String contactPersonId, SalutaionMaster salutaionMaster, String suppId, String contactPersonFname, String contactPersonLname, String contactPersonFunction, int contactPersonPhone, String contactPersonEmail, String termsandcondition) {
       this.contactPersonId = contactPersonId;
       this.salutaionMaster = salutaionMaster;
       this.suppId = suppId;
       this.contactPersonFname = contactPersonFname;
       this.contactPersonLname = contactPersonLname;
       this.contactPersonFunction = contactPersonFunction;
       this.contactPersonPhone = contactPersonPhone;
       this.contactPersonEmail = contactPersonEmail;
       this.termsandcondition = termsandcondition;
    }
   
    public String getContactPersonId() {
        return this.contactPersonId;
    }
    
    public void setContactPersonId(String contactPersonId) {
        this.contactPersonId = contactPersonId;
    }
    public SalutaionMaster getSalutaionMaster() {
        return this.salutaionMaster;
    }
    
    public void setSalutaionMaster(SalutaionMaster salutaionMaster) {
        this.salutaionMaster = salutaionMaster;
    }
    public String getSuppId() {
        return this.suppId;
    }
    
    public void setSuppId(String suppId) {
        this.suppId = suppId;
    }
    public String getContactPersonFname() {
        return this.contactPersonFname;
    }
    
    public void setContactPersonFname(String contactPersonFname) {
        this.contactPersonFname = contactPersonFname;
    }
    public String getContactPersonLname() {
        return this.contactPersonLname;
    }
    
    public void setContactPersonLname(String contactPersonLname) {
        this.contactPersonLname = contactPersonLname;
    }
    public String getContactPersonFunction() {
        return this.contactPersonFunction;
    }
    
    public void setContactPersonFunction(String contactPersonFunction) {
        this.contactPersonFunction = contactPersonFunction;
    }
    public int getContactPersonPhone() {
        return this.contactPersonPhone;
    }
    
    public void setContactPersonPhone(int contactPersonPhone) {
        this.contactPersonPhone = contactPersonPhone;
    }
    public String getContactPersonEmail() {
        return this.contactPersonEmail;
    }
    
    public void setContactPersonEmail(String contactPersonEmail) {
        this.contactPersonEmail = contactPersonEmail;
    }
    public String getTermsandcondition() {
        return this.termsandcondition;
    }
    
    public void setTermsandcondition(String termsandcondition) {
        this.termsandcondition = termsandcondition;
    }




}


