package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierStatusMaster generated by hbm2java
 */
public class SupplierStatusMaster  implements java.io.Serializable {


     private String suppStatusId;
     private String suppStatusDesc;
     private Set supplierMasters = new HashSet(0);

    public SupplierStatusMaster() {
    }

	
    public SupplierStatusMaster(String suppStatusId, String suppStatusDesc) {
        this.suppStatusId = suppStatusId;
        this.suppStatusDesc = suppStatusDesc;
    }
    public SupplierStatusMaster(String suppStatusId, String suppStatusDesc, Set supplierMasters) {
       this.suppStatusId = suppStatusId;
       this.suppStatusDesc = suppStatusDesc;
       this.supplierMasters = supplierMasters;
    }
   
    public String getSuppStatusId() {
        return this.suppStatusId;
    }
    
    public void setSuppStatusId(String suppStatusId) {
        this.suppStatusId = suppStatusId;
    }
    public String getSuppStatusDesc() {
        return this.suppStatusDesc;
    }
    
    public void setSuppStatusDesc(String suppStatusDesc) {
        this.suppStatusDesc = suppStatusDesc;
    }
    public Set getSupplierMasters() {
        return this.supplierMasters;
    }
    
    public void setSupplierMasters(Set supplierMasters) {
        this.supplierMasters = supplierMasters;
    }




}


