package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierQuatationMaster generated by hbm2java
 */
public class SupplierQuatationMaster  implements java.io.Serializable {


     private String suppQuatationId;
     private CurrencyMaster currencyMaster;
     private RequirementMaster requirementMaster;
     private SupplierMaster supplierMaster;
     private UnitMeasureMaster unitMeasureMaster;
     private String proposedcost;
     private String techSpecification;
     private String remarks;
     private String techFeedbackStatus;
     private String financFeedbackStatus;
     private Set sampleProductionApprovals = new HashSet(0);
     private Set financialFeedbackMasters = new HashSet(0);
     private Set sampleAdminApprovals = new HashSet(0);
     private Set sampleTechApprovals = new HashSet(0);
     private Set sampleFinancialApprovals = new HashSet(0);
     private Set technicalFeedbackMasters = new HashSet(0);
     private Set sampleAdminRequests = new HashSet(0);

    public SupplierQuatationMaster() {
    }

	
    public SupplierQuatationMaster(String suppQuatationId, CurrencyMaster currencyMaster, RequirementMaster requirementMaster, SupplierMaster supplierMaster, UnitMeasureMaster unitMeasureMaster, String proposedcost, String techSpecification, String remarks, String techFeedbackStatus, String financFeedbackStatus) {
        this.suppQuatationId = suppQuatationId;
        this.currencyMaster = currencyMaster;
        this.requirementMaster = requirementMaster;
        this.supplierMaster = supplierMaster;
        this.unitMeasureMaster = unitMeasureMaster;
        this.proposedcost = proposedcost;
        this.techSpecification = techSpecification;
        this.remarks = remarks;
        this.techFeedbackStatus = techFeedbackStatus;
        this.financFeedbackStatus = financFeedbackStatus;
    }
    public SupplierQuatationMaster(String suppQuatationId, CurrencyMaster currencyMaster, RequirementMaster requirementMaster, SupplierMaster supplierMaster, UnitMeasureMaster unitMeasureMaster, String proposedcost, String techSpecification, String remarks, String techFeedbackStatus, String financFeedbackStatus, Set sampleProductionApprovals, Set financialFeedbackMasters, Set sampleAdminApprovals, Set sampleTechApprovals, Set sampleFinancialApprovals, Set technicalFeedbackMasters, Set sampleAdminRequests) {
       this.suppQuatationId = suppQuatationId;
       this.currencyMaster = currencyMaster;
       this.requirementMaster = requirementMaster;
       this.supplierMaster = supplierMaster;
       this.unitMeasureMaster = unitMeasureMaster;
       this.proposedcost = proposedcost;
       this.techSpecification = techSpecification;
       this.remarks = remarks;
       this.techFeedbackStatus = techFeedbackStatus;
       this.financFeedbackStatus = financFeedbackStatus;
       this.sampleProductionApprovals = sampleProductionApprovals;
       this.financialFeedbackMasters = financialFeedbackMasters;
       this.sampleAdminApprovals = sampleAdminApprovals;
       this.sampleTechApprovals = sampleTechApprovals;
       this.sampleFinancialApprovals = sampleFinancialApprovals;
       this.technicalFeedbackMasters = technicalFeedbackMasters;
       this.sampleAdminRequests = sampleAdminRequests;
    }
   
    public String getSuppQuatationId() {
        return this.suppQuatationId;
    }
    
    public void setSuppQuatationId(String suppQuatationId) {
        this.suppQuatationId = suppQuatationId;
    }
    public CurrencyMaster getCurrencyMaster() {
        return this.currencyMaster;
    }
    
    public void setCurrencyMaster(CurrencyMaster currencyMaster) {
        this.currencyMaster = currencyMaster;
    }
    public RequirementMaster getRequirementMaster() {
        return this.requirementMaster;
    }
    
    public void setRequirementMaster(RequirementMaster requirementMaster) {
        this.requirementMaster = requirementMaster;
    }
    public SupplierMaster getSupplierMaster() {
        return this.supplierMaster;
    }
    
    public void setSupplierMaster(SupplierMaster supplierMaster) {
        this.supplierMaster = supplierMaster;
    }
    public UnitMeasureMaster getUnitMeasureMaster() {
        return this.unitMeasureMaster;
    }
    
    public void setUnitMeasureMaster(UnitMeasureMaster unitMeasureMaster) {
        this.unitMeasureMaster = unitMeasureMaster;
    }
    public String getProposedcost() {
        return this.proposedcost;
    }
    
    public void setProposedcost(String proposedcost) {
        this.proposedcost = proposedcost;
    }
    public String getTechSpecification() {
        return this.techSpecification;
    }
    
    public void setTechSpecification(String techSpecification) {
        this.techSpecification = techSpecification;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getTechFeedbackStatus() {
        return this.techFeedbackStatus;
    }
    
    public void setTechFeedbackStatus(String techFeedbackStatus) {
        this.techFeedbackStatus = techFeedbackStatus;
    }
    public String getFinancFeedbackStatus() {
        return this.financFeedbackStatus;
    }
    
    public void setFinancFeedbackStatus(String financFeedbackStatus) {
        this.financFeedbackStatus = financFeedbackStatus;
    }
    public Set getSampleProductionApprovals() {
        return this.sampleProductionApprovals;
    }
    
    public void setSampleProductionApprovals(Set sampleProductionApprovals) {
        this.sampleProductionApprovals = sampleProductionApprovals;
    }
    public Set getFinancialFeedbackMasters() {
        return this.financialFeedbackMasters;
    }
    
    public void setFinancialFeedbackMasters(Set financialFeedbackMasters) {
        this.financialFeedbackMasters = financialFeedbackMasters;
    }
    public Set getSampleAdminApprovals() {
        return this.sampleAdminApprovals;
    }
    
    public void setSampleAdminApprovals(Set sampleAdminApprovals) {
        this.sampleAdminApprovals = sampleAdminApprovals;
    }
    public Set getSampleTechApprovals() {
        return this.sampleTechApprovals;
    }
    
    public void setSampleTechApprovals(Set sampleTechApprovals) {
        this.sampleTechApprovals = sampleTechApprovals;
    }
    public Set getSampleFinancialApprovals() {
        return this.sampleFinancialApprovals;
    }
    
    public void setSampleFinancialApprovals(Set sampleFinancialApprovals) {
        this.sampleFinancialApprovals = sampleFinancialApprovals;
    }
    public Set getTechnicalFeedbackMasters() {
        return this.technicalFeedbackMasters;
    }
    
    public void setTechnicalFeedbackMasters(Set technicalFeedbackMasters) {
        this.technicalFeedbackMasters = technicalFeedbackMasters;
    }
    public Set getSampleAdminRequests() {
        return this.sampleAdminRequests;
    }
    
    public void setSampleAdminRequests(Set sampleAdminRequests) {
        this.sampleAdminRequests = sampleAdminRequests;
    }




}


