package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA



/**
 * SupplierGoodwillMaster generated by hbm2java
 */
public class SupplierGoodwillMaster  implements java.io.Serializable {


     private String goodwillId;
     private String goodwillDesc;

    public SupplierGoodwillMaster() {
    }

    public SupplierGoodwillMaster(String goodwillId, String goodwillDesc) {
       this.goodwillId = goodwillId;
       this.goodwillDesc = goodwillDesc;
    }
   
    public String getGoodwillId() {
        return this.goodwillId;
    }
    
    public void setGoodwillId(String goodwillId) {
        this.goodwillId = goodwillId;
    }
    public String getGoodwillDesc() {
        return this.goodwillDesc;
    }
    
    public void setGoodwillDesc(String goodwillDesc) {
        this.goodwillDesc = goodwillDesc;
    }




}


