package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA



/**
 * SupplierHistory generated by hbm2java
 */
public class SupplierHistory  implements java.io.Serializable {


     private String suppHid;
     private String suppName;
     private String contactPersonFname;
     private String contactPersonLname;
     private String contactPersonFunction;
     private String contactPersonPhone;
     private String contactPersonEmail;
     private String termsandcondition;
     private String techFeedback;
     private String finFeedback;
     private String opFeedback;

    public SupplierHistory() {
    }

    public SupplierHistory(String suppHid, String suppName, String contactPersonFname, String contactPersonLname, String contactPersonFunction, String contactPersonPhone, String contactPersonEmail, String termsandcondition, String techFeedback, String finFeedback, String opFeedback) {
       this.suppHid = suppHid;
       this.suppName = suppName;
       this.contactPersonFname = contactPersonFname;
       this.contactPersonLname = contactPersonLname;
       this.contactPersonFunction = contactPersonFunction;
       this.contactPersonPhone = contactPersonPhone;
       this.contactPersonEmail = contactPersonEmail;
       this.termsandcondition = termsandcondition;
       this.techFeedback = techFeedback;
       this.finFeedback = finFeedback;
       this.opFeedback = opFeedback;
    }
   
    public String getSuppHid() {
        return this.suppHid;
    }
    
    public void setSuppHid(String suppHid) {
        this.suppHid = suppHid;
    }
    public String getSuppName() {
        return this.suppName;
    }
    
    public void setSuppName(String suppName) {
        this.suppName = suppName;
    }
    public String getContactPersonFname() {
        return this.contactPersonFname;
    }
    
    public void setContactPersonFname(String contactPersonFname) {
        this.contactPersonFname = contactPersonFname;
    }
    public String getContactPersonLname() {
        return this.contactPersonLname;
    }
    
    public void setContactPersonLname(String contactPersonLname) {
        this.contactPersonLname = contactPersonLname;
    }
    public String getContactPersonFunction() {
        return this.contactPersonFunction;
    }
    
    public void setContactPersonFunction(String contactPersonFunction) {
        this.contactPersonFunction = contactPersonFunction;
    }
    public String getContactPersonPhone() {
        return this.contactPersonPhone;
    }
    
    public void setContactPersonPhone(String contactPersonPhone) {
        this.contactPersonPhone = contactPersonPhone;
    }
    public String getContactPersonEmail() {
        return this.contactPersonEmail;
    }
    
    public void setContactPersonEmail(String contactPersonEmail) {
        this.contactPersonEmail = contactPersonEmail;
    }
    public String getTermsandcondition() {
        return this.termsandcondition;
    }
    
    public void setTermsandcondition(String termsandcondition) {
        this.termsandcondition = termsandcondition;
    }
    public String getTechFeedback() {
        return this.techFeedback;
    }
    
    public void setTechFeedback(String techFeedback) {
        this.techFeedback = techFeedback;
    }
    public String getFinFeedback() {
        return this.finFeedback;
    }
    
    public void setFinFeedback(String finFeedback) {
        this.finFeedback = finFeedback;
    }
    public String getOpFeedback() {
        return this.opFeedback;
    }
    
    public void setOpFeedback(String opFeedback) {
        this.opFeedback = opFeedback;
    }




}


