package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TechnicalFeedbackMaster generated by hbm2java
 */
public class TechnicalFeedbackMaster  implements java.io.Serializable {


     private String techFeedbackId;
     private SupplierQuatationMaster supplierQuatationMaster;
     private RatingMaster ratingMaster;
     private MaterialTechGoodwillMaster materialTechGoodwillMaster;
     private String techApproved;
     private String feedback;
     private String feedbackBy;
     private Date feedBackDate;

    public TechnicalFeedbackMaster() {
    }

    public TechnicalFeedbackMaster(String techFeedbackId, SupplierQuatationMaster supplierQuatationMaster, RatingMaster ratingMaster, MaterialTechGoodwillMaster materialTechGoodwillMaster, String techApproved, String feedback, String feedbackBy, Date feedBackDate) {
       this.techFeedbackId = techFeedbackId;
       this.supplierQuatationMaster = supplierQuatationMaster;
       this.ratingMaster = ratingMaster;
       this.materialTechGoodwillMaster = materialTechGoodwillMaster;
       this.techApproved = techApproved;
       this.feedback = feedback;
       this.feedbackBy = feedbackBy;
       this.feedBackDate = feedBackDate;
    }
   
    public String getTechFeedbackId() {
        return this.techFeedbackId;
    }
    
    public void setTechFeedbackId(String techFeedbackId) {
        this.techFeedbackId = techFeedbackId;
    }
    public SupplierQuatationMaster getSupplierQuatationMaster() {
        return this.supplierQuatationMaster;
    }
    
    public void setSupplierQuatationMaster(SupplierQuatationMaster supplierQuatationMaster) {
        this.supplierQuatationMaster = supplierQuatationMaster;
    }
    public RatingMaster getRatingMaster() {
        return this.ratingMaster;
    }
    
    public void setRatingMaster(RatingMaster ratingMaster) {
        this.ratingMaster = ratingMaster;
    }
    public MaterialTechGoodwillMaster getMaterialTechGoodwillMaster() {
        return this.materialTechGoodwillMaster;
    }
    
    public void setMaterialTechGoodwillMaster(MaterialTechGoodwillMaster materialTechGoodwillMaster) {
        this.materialTechGoodwillMaster = materialTechGoodwillMaster;
    }
    public String getTechApproved() {
        return this.techApproved;
    }
    
    public void setTechApproved(String techApproved) {
        this.techApproved = techApproved;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public String getFeedbackBy() {
        return this.feedbackBy;
    }
    
    public void setFeedbackBy(String feedbackBy) {
        this.feedbackBy = feedbackBy;
    }
    public Date getFeedBackDate() {
        return this.feedBackDate;
    }
    
    public void setFeedBackDate(Date feedBackDate) {
        this.feedBackDate = feedBackDate;
    }




}


