package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UnitMeasureMaster generated by hbm2java
 */
public class UnitMeasureMaster  implements java.io.Serializable {


     private String unitId;
     private String unitOfMeasure;
     private Set requirementMasters = new HashSet(0);
     private Set supplierQuatationMasters = new HashSet(0);
     private Set sampleDemandSpecfications = new HashSet(0);
     private Set sampleRequisitionAcceptanceDetailses = new HashSet(0);

    public UnitMeasureMaster() {
    }

	
    public UnitMeasureMaster(String unitId, String unitOfMeasure) {
        this.unitId = unitId;
        this.unitOfMeasure = unitOfMeasure;
    }
    public UnitMeasureMaster(String unitId, String unitOfMeasure, Set requirementMasters, Set supplierQuatationMasters, Set sampleDemandSpecfications, Set sampleRequisitionAcceptanceDetailses) {
       this.unitId = unitId;
       this.unitOfMeasure = unitOfMeasure;
       this.requirementMasters = requirementMasters;
       this.supplierQuatationMasters = supplierQuatationMasters;
       this.sampleDemandSpecfications = sampleDemandSpecfications;
       this.sampleRequisitionAcceptanceDetailses = sampleRequisitionAcceptanceDetailses;
    }
   
    public String getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }
    public String getUnitOfMeasure() {
        return this.unitOfMeasure;
    }
    
    public void setUnitOfMeasure(String unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }
    public Set getRequirementMasters() {
        return this.requirementMasters;
    }
    
    public void setRequirementMasters(Set requirementMasters) {
        this.requirementMasters = requirementMasters;
    }
    public Set getSupplierQuatationMasters() {
        return this.supplierQuatationMasters;
    }
    
    public void setSupplierQuatationMasters(Set supplierQuatationMasters) {
        this.supplierQuatationMasters = supplierQuatationMasters;
    }
    public Set getSampleDemandSpecfications() {
        return this.sampleDemandSpecfications;
    }
    
    public void setSampleDemandSpecfications(Set sampleDemandSpecfications) {
        this.sampleDemandSpecfications = sampleDemandSpecfications;
    }
    public Set getSampleRequisitionAcceptanceDetailses() {
        return this.sampleRequisitionAcceptanceDetailses;
    }
    
    public void setSampleRequisitionAcceptanceDetailses(Set sampleRequisitionAcceptanceDetailses) {
        this.sampleRequisitionAcceptanceDetailses = sampleRequisitionAcceptanceDetailses;
    }




}


