package classes;
// Generated Nov 14, 2011 2:32:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserMaster generated by hbm2java
 */
public class UserMaster  implements java.io.Serializable {


     private String userId;
     private EmployeeMaster employeeMaster;
     private String loginName;
     private String password;
     private Set resourceMasters = new HashSet(0);

    public UserMaster() {
    }

	
    public UserMaster(String userId, EmployeeMaster employeeMaster, String loginName, String password) {
        this.userId = userId;
        this.employeeMaster = employeeMaster;
        this.loginName = loginName;
        this.password = password;
    }
    public UserMaster(String userId, EmployeeMaster employeeMaster, String loginName, String password, Set resourceMasters) {
       this.userId = userId;
       this.employeeMaster = employeeMaster;
       this.loginName = loginName;
       this.password = password;
       this.resourceMasters = resourceMasters;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public EmployeeMaster getEmployeeMaster() {
        return this.employeeMaster;
    }
    
    public void setEmployeeMaster(EmployeeMaster employeeMaster) {
        this.employeeMaster = employeeMaster;
    }
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getResourceMasters() {
        return this.resourceMasters;
    }
    
    public void setResourceMasters(Set resourceMasters) {
        this.resourceMasters = resourceMasters;
    }




}


